apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: uppl5m5kt-java-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uppl5m5kt-java-quarkus 
  name: uppl5m5kt-java-quarkus
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: uppl5m5kt-java-quarkus
    weight: 100 
